// <auto-generated />
using System;
using MQEntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MQEntityFrameworkCore.Migrations
{
    [DbContext(typeof(MQDbcontext))]
    partial class MQDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MQEntityModal.Modal.Role", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Memo");

                    b.Property<string>("Name");

                    b.HasKey("guid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MQEntityModal.Modal.User", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Memo");

                    b.Property<string>("Name");

                    b.HasKey("guid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
